#!/usr/bin/env python3
"""Generates C++ headers from the design sheets (the sheets are the source of
truth: change the sheet first, then regenerate). Refuses to run while the
preflight reports errors; open items (unverified hooks) do not block it."""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import preflight  # noqa: E402

ROOT = preflight.ROOT
OUT = ROOT / "src" / "generated"
NS = "timerewind"

FIELD_CPP = {"vec3": "Vec3", "f32": "float", "i32": "int32_t"}
CONFIG_CPP = {"i32": "int32_t", "f32": "float", "bool": "bool"}
LERP_FN = {
    ("vec3", "lerp"): "lerp_vec3",
    ("f32", "lerp"): "lerp_f32",
    ("f32", "lerp_angle"): "lerp_angle_deg",
}
BANNER = "// GENERATED by tools/gen.py from sheets/{sheet}.json - do not edit by hand."


def ident(text):
    return text.replace(".", "_")


def num(value, ctype):
    if ctype == "f32":
        return repr(float(value)) + "f"
    return str(int(value))


def q(value):
    return json.dumps(value or "")


def gen_snapshot(rows):
    out = [
        BANNER.format(sheet="fields"),
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        '#include "../types.h"',
        "",
        f"namespace {NS} {{",
        "",
        "struct Snapshot {",
    ]
    for r in rows:
        out.append(f"    {FIELD_CPP[r['type']]} {ident(r['id'])}{{}};  // {r['restore_policy']}")
    out += [
        "};",
        "",
        "inline Snapshot snapshot_lerp(const Snapshot& a, const Snapshot& b, float t) {",
        "    Snapshot r;",
    ]
    for r in rows:
        name = ident(r["id"])
        if r["restore_policy"] == "step":
            out.append(f"    r.{name} = a.{name};")
        else:
            fn = LERP_FN[(r["type"], r["restore_policy"])]
            out.append(f"    r.{name} = {fn}(a.{name}, b.{name}, t);")
    out += ["    return r;", "}", "", f"}}  // namespace {NS}", ""]
    return "\n".join(out)


def gen_config(rows):
    out = [
        BANNER.format(sheet="config"),
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string>",
        "",
        '#include "../types.h"',
        "",
        f"namespace {NS} {{",
        "",
        "struct Config {",
    ]
    for r in rows:
        t = r["type"]
        default = ("true" if r["default"] else "false") if t == "bool" else num(r["default"], t)
        out.append(f"    {CONFIG_CPP[t]} {r['key']} = {default};")
    out += [
        "};",
        "",
        "// Returns true when `key` is a known setting. A bad value keeps the current one.",
        "inline bool config_set(Config& c, const std::string& key, const std::string& value) {",
    ]
    for r in rows:
        t, k = r["type"], r["key"]
        if t == "i32":
            expr = f"clamp_i32(parse_i32(value, c.{k}), {num(r['min'], t)}, {num(r['max'], t)})"
        elif t == "f32":
            expr = f"clamp_f32(parse_f32(value, c.{k}), {num(r['min'], t)}, {num(r['max'], t)})"
        else:
            expr = f"parse_bool(value, c.{k})"
        out.append(f'    if (key == "{k}") {{ c.{k} = {expr}; return true; }}')
    out += ["    return false;", "}", "", f"}}  // namespace {NS}", ""]
    return "\n".join(out)


def gen_hooks(rows):
    out = [
        BANNER.format(sheet="hooks"),
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        f"namespace {NS} {{",
        "",
        "struct HookInfo {",
        "    const char* id;",
        "    const char* kind;",
        "    const char* target;",
        "    const char* status;",
        "};",
        "",
        "inline constexpr HookInfo kHooks[] = {",
    ]
    for r in rows:
        out.append(f"    {{{q(r['id'])}, {q(r['kind'])}, {q(r['target'])}, {q(r['status'])}}},")
    out += [
        "};",
        "",
        "inline constexpr std::size_t kHookCount = sizeof(kHooks) / sizeof(kHooks[0]);",
        "",
        "// The plugin must stay idle unless every hook is verified for the installed game build.",
        "inline bool all_hooks_verified() {",
        "    for (const HookInfo& h : kHooks) {",
        '        if (std::string_view(h.status) != "verified") return false;',
        "    }",
        "    return true;",
        "}",
        "",
        f"}}  // namespace {NS}",
        "",
    ]
    return "\n".join(out)


def main():
    sheets = preflight.load_sheets()
    errors, _todo = preflight.run(sheets)
    if errors:
        print("Preflight has errors, not generating:")
        for e in errors:
            print(f"  - {e}")
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    files = {
        "snapshot.h": gen_snapshot(sheets["fields"]["rows"]),
        "config.h": gen_config(sheets["config"]["rows"]),
        "hooks.h": gen_hooks(sheets["hooks"]["rows"]),
    }
    for name, text in files.items():
        (OUT / name).write_text(text, encoding="utf-8")
    print(f"Generated {len(files)} headers in {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
